config/routes.rb
Rails.application.routes.draw do

  resources :pedidos
  resources :funcionarios
  devise_for :donos, :controllers => {:registrations => "registrations"}
  resources :donos
  resources :cargos
  resources :clientes
  resources :items

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: "home#index"

end

app/models/cliente.rb
require 'cpf_cnpj'

class Cliente < ApplicationRecord

  has_one :pedido, dependent: :destroy

  validates :nome, presence: true, length: {in: 2..50}
  validate :cpf_valido

  def cpf_valido
    if cpf.present? && !CPF.valid?(cpf)
      errors.add(:cpf, "formato ou numero errado")
    end
  end
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: %i[ show edit update destroy ]
  before_action :authenticate_dono!

  # GET /clientes or /clientes.json
  def index
    @clientes = Cliente.all
  end

  # GET /clientes/1 or /clientes/1.json
  def show
  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new
  end

  # GET /clientes/1/edit
  def edit
  end

  # POST /clientes or /clientes.json
  def create
    @cliente = Cliente.new(cliente_params)

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to cliente_url(@cliente), notice: "Cliente was successfully created." }
        format.json { render :show, status: :created, location: @cliente }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clientes/1 or /clientes/1.json
  def update
    respond_to do |format|
      if @cliente.update(cliente_params)
        format.html { redirect_to cliente_url(@cliente), notice: "Cliente was successfully updated." }
        format.json { render :show, status: :ok, location: @cliente }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1 or /clientes/1.json
  def destroy
    @cliente.destroy

    respond_to do |format|
      format.html { redirect_to clientes_url, notice: "Cliente was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cliente_params
      params.require(:cliente).permit(:nome, :cpf)
    end
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/views/clientes/_cliente.html.erb
<div id="<%= dom_id cliente %>">
  <p>
    <strong>Nome:</strong>
    <%= cliente.nome %>
  </p>

  <p>
    <strong>Cpf:</strong>
    <%= cliente.cpf %>
  </p>

</div>

app/views/clientes/_form.html.erb
<%= form_with(model: cliente) do |form| %>
  <% if cliente.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(cliente.errors.count, "error") %> prohibited this cliente from being saved:</h2>

      <ul>
        <% cliente.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nome, style: "display: block" %>
    <%= form.text_field :nome %>
  </div>

  <div>
    <%= form.label :cpf, style: "display: block" %>
    <%= form.text_field :cpf %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/clientes/edit.html.erb
<h1>Editing cliente</h1>

<%= render "form", cliente: @cliente %>

<br>

<div>
  <%= link_to "Show this cliente", @cliente %> |
  <%= link_to "Back to clientes", clientes_path %>
</div>

app/views/clientes/index.html.erb
<h1>Clientes</h1>

<div id="clientes">
  <% @clientes.each do |cliente| %>
    <%= render cliente %>
    <p>
      <%= link_to "Show this cliente", cliente %>
    </p>
  <% end %>
</div>

<%= link_to "New cliente", new_cliente_path %>

app/views/clientes/new.html.erb
<h1>New cliente</h1>

<%= render "form", cliente: @cliente %>

<br>

<div>
  <%= link_to "Back to clientes", clientes_path %>
</div>

app/views/clientes/show.html.erb
<%= render @cliente %>

<div>
  <%= link_to "Edit this cliente", edit_cliente_path(@cliente) %> |
  <%= link_to "Back to clientes", clientes_path %>

  <%= button_to "Destroy this cliente", @cliente, method: :delete %>
</div>