config/routes.rb
Rails.application.routes.draw do

  resources :pedidos
  resources :funcionarios
  devise_for :donos, :controllers => {:registrations => "registrations"}
  resources :donos
  resources :cargos
  resources :clientes
  resources :items

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: "home#index"

end

app/models/cargo.rb
class Cargo < ApplicationRecord

  has_many :funcionarios

  validates :funcao, presence: true, length: {in: 2..50}
  validates :salario, presence: true, length: {in: 2..50}, numericality: {only_integer: true}
end

app/controllers/cargos_controller.rb
class CargosController < ApplicationController
  before_action :set_cargo, only: %i[ show edit update destroy ]
  before_action :authenticate_dono!

  # GET /cargos or /cargos.json
  def index
    @cargos = Cargo.all
  end

  # GET /cargos/1 or /cargos/1.json
  def show
  end

  # GET /cargos/new
  def new
    @cargo = Cargo.new
  end

  # GET /cargos/1/edit
  def edit
  end

  # POST /cargos or /cargos.json
  def create
    @cargo = Cargo.new(cargo_params)

    respond_to do |format|
      if @cargo.save
        format.html { redirect_to cargo_url(@cargo), notice: "Cargo was successfully created." }
        format.json { render :show, status: :created, location: @cargo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cargo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cargos/1 or /cargos/1.json
  def update
    respond_to do |format|
      if @cargo.update(cargo_params)
        format.html { redirect_to cargo_url(@cargo), notice: "Cargo was successfully updated." }
        format.json { render :show, status: :ok, location: @cargo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cargo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cargos/1 or /cargos/1.json
  def destroy
    @cargo.destroy

    respond_to do |format|
      format.html { redirect_to cargos_url, notice: "Cargo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cargo
      @cargo = Cargo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cargo_params
      params.require(:cargo).permit(:funcao, :salario)
    end
end

app/helpers/cargos_helper.rb
module CargosHelper
end

app/views/cargos/_cargo.html.erb
<div id="<%= dom_id cargo %>">
  <p>
    <strong>Funcao:</strong>
    <%= cargo.funcao %>
  </p>

  <p>
    <strong>Salario:</strong>
    <%= cargo.salario %>
  </p>

</div>

app/views/cargos/_form.html.erb
<%= form_with(model: cargo) do |form| %>
  <% if cargo.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(cargo.errors.count, "error") %> prohibited this cargo from being saved:</h2>

      <ul>
        <% cargo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :funcao, style: "display: block" %>
    <%= form.text_field :funcao %>
  </div>

  <div>
    <%= form.label :salario, style: "display: block" %>
    <%= form.number_field :salario %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/cargos/edit.html.erb
<h1>Editing cargo</h1>

<%= render "form", cargo: @cargo %>

<br>

<div>
  <%= link_to "Show this cargo", @cargo %> |
  <%= link_to "Back to cargos", cargos_path %>
</div>

app/views/cargos/index.html.erb
<h1>Cargos</h1>

<div id="cargos">
  <% @cargos.each do |cargo| %>
    <%= render cargo %>
    <p>
      <%= link_to "Show this cargo", cargo %>
    </p>
  <% end %>
</div>

<%= link_to "New cargo", new_cargo_path %>

app/views/cargos/new.html.erb
<h1>New cargo</h1>

<%= render "form", cargo: @cargo %>

<br>

<div>
  <%= link_to "Back to cargos", cargos_path %>
</div>

app/views/cargos/show.html.erb
<%= render @cargo %>

<div>
  <%= link_to "Edit this cargo", edit_cargo_path(@cargo) %> |
  <%= link_to "Back to cargos", cargos_path %>

  <%= button_to "Destroy this cargo", @cargo, method: :delete %>
</div>