config/routes.rb
Rails.application.routes.draw do

  resources :pedidos
  resources :funcionarios
  devise_for :donos, :controllers => {:registrations => "registrations"}
  resources :donos
  resources :cargos
  resources :clientes
  resources :items

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: "home#index"

end

app/models/funcionario.rb
require 'cpf_cnpj'
class Funcionario < ApplicationRecord

  belongs_to :cargo
  belongs_to :dono
  accepts_nested_attributes_for :cargo

  validates :nome, presence: true, length: {in: 2..50}
  validates :email, presence: true, format: {with: URI::MailTo::EMAIL_REGEXP}
  validate :nascimento_valido
  validate :cpf_valido

  def cpf_valido
    if cpf.present? && !CPF.valid?(cpf)
      errors.add(:cpf, "formato ou numero errado")
    end
  end
  def nascimento_valido
    if nascimento.present? && nascimento > Time.zone.today
      errors.add(:data, "Sua data de nascimento é inválida!")
    end
  end
end

app/controllers/funcionarios_controller.rb
class FuncionariosController < ApplicationController
  before_action :set_funcionario, only: %i[ show edit update destroy ]
  before_action :authenticate_dono!


  # GET /funcionarios or /funcionarios.json
  def index
    @funcionarios = Funcionario.all
  end

  # GET /funcionarios/1 or /funcionarios/1.json
  def show
  end

  # GET /funcionarios/new
  def new

    @funcionario = Funcionario.new
  end

  # GET /funcionarios/1/edit
  def edit
  end

  # POST /funcionarios or /funcionarios.json
  def create
    @funcionario = Funcionario.new(funcionario_params)
    @cargo = Cargo.find(funcionario_params[:cargo_id])
    @cargo.funcionarios << @funcionario

    respond_to do |format|
      if @funcionario.save
        format.html { redirect_to funcionario_url(@funcionario), notice: "Funcionario was successfully created." }
        format.json { render :show, status: :created, location: @funcionario }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @funcionario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /funcionarios/1 or /funcionarios/1.json
  def update
    respond_to do |format|
      if @funcionario.update(funcionario_params)
        format.html { redirect_to funcionario_url(@funcionario), notice: "Funcionario was successfully updated." }
        format.json { render :show, status: :ok, location: @funcionario }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @funcionario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /funcionarios/1 or /funcionarios/1.json
  def destroy
    @funcionario.destroy

    respond_to do |format|
      format.html { redirect_to funcionarios_url, notice: "Funcionario was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_funcionario
      @funcionario = Funcionario.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def funcionario_params
      params.require(:funcionario).permit(:nome, :cpf, :nascimento, :email, :cargo_id, :dono_id)
    end
end

app/helpers/funcionarios_helper.rb
module FuncionariosHelper
end

app/views/funcionarios/_form.html.erb
<%= form_with(model: funcionario) do |form| %>
  <% if funcionario.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(funcionario.errors.count, "error") %> prohibited this funcionario from being saved:</h2>

      <ul>
        <% funcionario.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>



  <div>
    <%= form.label :nome, style: "display: block" %>
    <%= form.text_field :nome %>
  </div>

  <div>
    <%= form.label :cpf, style: "display: block" %>
    <%= form.text_field :cpf %>
  </div>

  <div>
    <%= form.label :nascimento, style: "display: block" %>
    <%= form.date_field :nascimento %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :cargo_id%>
    <%= form.collection_select(:cargo_id, Cargo.all, :id, :funcao,{:selected => @funcionario.cargo_id})%>
  </div>
  <%= form.hidden_field :dono_id, value: current_dono.id %>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/funcionarios/_funcionario.html.erb
<div id="<%= dom_id funcionario %>">
  <p>
    <strong>Nome:</strong>
    <%= funcionario.nome %>
  </p>

  <p>
    <strong>Cpf:</strong>
    <%= funcionario.cpf %>
  </p>

  <p>
    <strong>Nascimento:</strong>
    <%= funcionario.nascimento %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= funcionario.email %>
  </p>

  <p>
    <strong>Cargo:</strong>
    <%= Cargo.find(@funcionario.cargo_id).funcao %>
  </p>

</div>

app/views/funcionarios/edit.html.erb
<h1>Editing funcionario</h1>

<%= render "form", funcionario: @funcionario %>

<br>

<div>
  <%= link_to "Show this funcionario", @funcionario %> |
  <%= link_to "Back to funcionarios", funcionarios_path %>
</div>

app/views/funcionarios/index.html.erb
<h1>Funcionarios</h1>

<div id="funcionarios">
  <% @funcionarios.each do |funcionario| %>
    <tr>
    <div id="<%= dom_id funcionario %>">
      <p>
        <strong>Nome:</strong>
        <%= funcionario.nome %>
      </p>

      <p>
        <strong>Cpf:</strong>
        <%= funcionario.cpf %>
      </p>

      <p>
        <strong>Nascimento:</strong>
        <%= funcionario.nascimento %>
      </p>

      <p>
        <strong>Email:</strong>
        <%= funcionario.email %>
      </p>

      <p>
        <strong>Cargo:</strong>
        <%=  Cargo.find(funcionario.cargo_id).funcao  %>
      </p>


      <p>
      <%= link_to "Show this funcionario", funcionario %>
      </p>
    </div>
    </tr>

  <% end %>
</div>

<%= link_to "New funcionario", new_funcionario_path %>

app/views/funcionarios/new.html.erb
<h1>New funcionario</h1>

<%= render "form", funcionario: @funcionario %>

<br>

<div>
  <%= link_to "Back to funcionarios", funcionarios_path %>
</div>

app/views/funcionarios/show.html.erb
<%= render @funcionario %>

<div>
  <%= link_to "Edit this funcionario", edit_funcionario_path(@funcionario) %> |
  <%= link_to "Back to funcionarios", funcionarios_path %>

  <%= button_to "Destroy this funcionario", @funcionario, method: :delete %>
</div>