config/routes.rb
Rails.application.routes.draw do

  resources :pedidos
  resources :funcionarios
  devise_for :donos, :controllers => {:registrations => "registrations"}
  resources :donos
  resources :cargos
  resources :clientes
  resources :items

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: "home#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ElefantePretoManagement</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-black">
    <div class="container-fluid">
      <a class="navbar-brand" href="/"  >Elefante Preto</a>

      <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <% if current_dono %>
            <li class="nav-item">
              <%= link_to "Donos", donos_path, class: "nav-link active" %>
            </li>
          <% end %>
          <li class="nav-item">
            <%= link_to "Cargos", cargos_path, class: "nav-link active" %>
          </li>
          <li class="nav-item">
            <%= link_to "Funcionarios", funcionarios_path, class: "nav-link active" %>
          </li>
          <li class="nav-item">
            <%= link_to "Cliente", clientes_path, class: "nav-link active" %>
          </li>
          <li class="nav-item">
            <%= link_to "Cardápio", items_path, class: "nav-link active" %>
          </li>
          <li class="nav-item">
            <%= link_to "Pedidos", pedidos_path, class: "nav-link active" %>
          </li>

        </ul>
      </div>
    </div>
  </nav>
  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>
    <%= yield %>
  </body>
</html>